-- ============================================================
-- PODIUM — MIGRATION 005: Classificações
-- ============================================================
-- Sistema de classificações:
--   • Tabela `competicoes` — define cada liga/torneio
--   • Tabela `classificacoes_ajustes` — pontos extra/penalizações manuais
--   • View `classificacao_publica` — calcula automaticamente a tabela
--     a partir dos resultados (agenda + manuais) + ajustes
--   • Top marcadores extraídos das estatísticas dos jogos
--
-- COMO CORRER:
--   Supabase Dashboard → SQL Editor → New query → colar tudo → Run
--
-- IDEMPOTENTE: pode correr múltiplas vezes sem problemas.
-- Pré-requisito: migrations 003 e 004 já corridas.
-- ============================================================

-- ============================================================
-- 1. TABELA: competicoes
--    Cada liga/torneio que tenha tabela classificativa
-- ============================================================
create table if not exists public.competicoes (
  id              bigint generated by default as identity primary key,
  nome            text not null,                          -- ex: "Liga Nacional 2025/26"
  slug            text unique not null,                   -- ex: "liga-nacional-2025-26"
  categoria_id    bigint references public.categorias(id) on delete cascade,
  -- Sistema de pontos (configurável por competição)
  pontos_vitoria  int default 3,
  pontos_empate   int default 1,
  pontos_derrota  int default 0,
  -- Visibilidade
  ativa           boolean default true,                   -- mostrar tabela classificativa
  publicada       boolean default true,                   -- visível ao público
  -- Datas
  data_inicio     date,
  data_fim        date,
  criada_em       timestamptz default now(),
  actualizada_em  timestamptz default now()
);

create index if not exists idx_competicoes_categoria on public.competicoes (categoria_id);
create index if not exists idx_competicoes_publicada on public.competicoes (publicada);

drop trigger if exists trg_competicoes_updated on public.competicoes;
create trigger trg_competicoes_updated
  before update on public.competicoes
  for each row execute function public.handle_updated_at();

-- ============================================================
-- 2. TABELA: classificacoes_ajustes
--    Para penalizações, bónus ou pontos atribuídos manualmente
--    (ex: clube perde 3 pontos por incumprimento)
-- ============================================================
create table if not exists public.classificacoes_ajustes (
  id            bigint generated by default as identity primary key,
  competicao_id bigint references public.competicoes(id) on delete cascade,
  equipa        text not null,
  pontos        int not null default 0,                   -- positivo OU negativo
  motivo        text,                                     -- ex: "Penalização disciplinar"
  criada_em     timestamptz default now(),
  criada_por    uuid references auth.users(id) on delete set null
);

create index if not exists idx_ajustes_competicao on public.classificacoes_ajustes (competicao_id);

-- ============================================================
-- 3. ROW LEVEL SECURITY
-- ============================================================
alter table public.competicoes              enable row level security;
alter table public.classificacoes_ajustes   enable row level security;

drop policy if exists "competicoes_public_read"     on public.competicoes;
drop policy if exists "competicoes_admin_read_all"  on public.competicoes;
drop policy if exists "competicoes_admin_write"     on public.competicoes;

create policy "competicoes_public_read"
  on public.competicoes for select using (publicada = true);
create policy "competicoes_admin_read_all"
  on public.competicoes for select using (public.is_admin());
create policy "competicoes_admin_write"
  on public.competicoes for all
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "ajustes_public_read"     on public.classificacoes_ajustes;
drop policy if exists "ajustes_admin_write"     on public.classificacoes_ajustes;

create policy "ajustes_public_read"
  on public.classificacoes_ajustes for select using (true);
create policy "ajustes_admin_write"
  on public.classificacoes_ajustes for all
  using (public.is_admin()) with check (public.is_admin());

-- ============================================================
-- 4. VIEW: jogos_classificacao
--    Une jogos da agenda terminados + resultados manuais
--    (sem filtrar por competicao_id — match-by-text de competicao)
-- ============================================================
drop view if exists public.jogos_classificacao;

create view public.jogos_classificacao as
-- Da agenda
select
  e.competicao         as competicao_nome,
  e.equipa_casa,
  e.equipa_fora,
  e.resultado_casa,
  e.resultado_fora,
  e.categoria_id,
  e.data_evento
from public.agenda_eventos e
where e.publicado = true
  and e.status = 'terminado'
  and e.resultado_casa is not null
  and e.resultado_fora is not null
  and e.competicao is not null
  and e.equipa_casa is not null
  and e.equipa_fora is not null

union all

-- Manuais
select
  r.competicao         as competicao_nome,
  r.equipa_casa,
  r.equipa_fora,
  r.resultado_casa,
  r.resultado_fora,
  r.categoria_id,
  r.data_evento
from public.resultados r
where r.publicado = true
  and r.competicao is not null;

grant select on public.jogos_classificacao to anon, authenticated;

-- ============================================================
-- 5. VIEW: classificacao_publica
--    Calcula J/V/E/D/GM/GS/DG/Pts por competição e equipa.
--    Junta também os ajustes manuais.
-- ============================================================
drop view if exists public.classificacao_publica;

create view public.classificacao_publica as
with
  -- Cada jogo gera DUAS linhas (uma por equipa) com a perspectiva dela
  jogos_expandidos as (
    select
      j.competicao_nome,
      j.categoria_id,
      j.equipa_casa as equipa,
      j.resultado_casa as gm,
      j.resultado_fora as gs,
      case
        when j.resultado_casa > j.resultado_fora then 'V'
        when j.resultado_casa < j.resultado_fora then 'D'
        else 'E'
      end as resultado
    from public.jogos_classificacao j
    union all
    select
      j.competicao_nome,
      j.categoria_id,
      j.equipa_fora as equipa,
      j.resultado_fora as gm,
      j.resultado_casa as gs,
      case
        when j.resultado_fora > j.resultado_casa then 'V'
        when j.resultado_fora < j.resultado_casa then 'D'
        else 'E'
      end as resultado
    from public.jogos_classificacao j
  ),
  -- Agregação por competição + equipa
  agregado as (
    select
      je.competicao_nome,
      je.categoria_id,
      je.equipa,
      count(*)                                       as jogos,
      count(*) filter (where je.resultado = 'V')     as vitorias,
      count(*) filter (where je.resultado = 'E')     as empates,
      count(*) filter (where je.resultado = 'D')     as derrotas,
      coalesce(sum(je.gm), 0)                        as gm,
      coalesce(sum(je.gs), 0)                        as gs
    from jogos_expandidos je
    group by je.competicao_nome, je.categoria_id, je.equipa
  )
select
  c.id            as competicao_id,
  c.nome          as competicao_nome,
  c.slug          as competicao_slug,
  c.categoria_id,
  cat.slug        as categoria_slug,
  cat.nome        as categoria_nome,
  cat.emoji       as categoria_emoji,
  cat.cor         as categoria_cor,
  ag.equipa,
  ag.jogos,
  ag.vitorias,
  ag.empates,
  ag.derrotas,
  ag.gm,
  ag.gs,
  (ag.gm - ag.gs) as diferenca_golos,
  (ag.vitorias * c.pontos_vitoria
   + ag.empates  * c.pontos_empate
   + ag.derrotas * c.pontos_derrota
   + coalesce(aj.ajuste_total, 0)
  )               as pontos,
  coalesce(aj.ajuste_total, 0) as ajuste_pontos
from public.competicoes c
left join public.categorias cat on cat.id = c.categoria_id
inner join agregado ag
  on ag.competicao_nome = c.nome
  and (ag.categoria_id = c.categoria_id or ag.categoria_id is null)
left join (
  select competicao_id, equipa, sum(pontos) as ajuste_total
  from public.classificacoes_ajustes
  group by competicao_id, equipa
) aj on aj.competicao_id = c.id and aj.equipa = ag.equipa
where c.publicada = true and c.ativa = true
order by c.nome, pontos desc, diferenca_golos desc, gm desc, ag.equipa;

grant select on public.classificacao_publica to anon, authenticated;

-- ============================================================
-- 6. VIEW: top_marcadores
--    Extrai golos das estatísticas dos jogos (jsonb)
--    Calcula golos por jogador, por competição
-- ============================================================
drop view if exists public.top_marcadores;

create view public.top_marcadores as
with
  -- Golos da agenda
  golos_agenda as (
    select
      e.competicao              as competicao_nome,
      e.categoria_id,
      stat->>'jogador'          as jogador,
      stat->>'equipa'           as equipa_lado,
      case stat->>'equipa'
        when 'casa' then e.equipa_casa
        when 'fora' then e.equipa_fora
      end                       as equipa
    from public.agenda_eventos e,
         lateral jsonb_array_elements(coalesce(e.estatisticas, '[]'::jsonb)) as stat
    where e.publicado = true
      and e.status = 'terminado'
      and stat->>'tipo' = 'golo'
      and stat->>'jogador' is not null
      and stat->>'jogador' <> ''
  ),
  -- Golos dos resultados manuais
  golos_manuais as (
    select
      r.competicao              as competicao_nome,
      r.categoria_id,
      stat->>'jogador'          as jogador,
      stat->>'equipa'           as equipa_lado,
      case stat->>'equipa'
        when 'casa' then r.equipa_casa
        when 'fora' then r.equipa_fora
      end                       as equipa
    from public.resultados r,
         lateral jsonb_array_elements(coalesce(r.estatisticas, '[]'::jsonb)) as stat
    where r.publicado = true
      and stat->>'tipo' = 'golo'
      and stat->>'jogador' is not null
      and stat->>'jogador' <> ''
  ),
  todos as (
    select * from golos_agenda
    union all
    select * from golos_manuais
  )
select
  c.id              as competicao_id,
  c.nome            as competicao_nome,
  c.slug            as competicao_slug,
  c.categoria_id,
  cat.slug          as categoria_slug,
  cat.nome          as categoria_nome,
  cat.emoji         as categoria_emoji,
  todos.jogador,
  max(todos.equipa) as equipa,
  count(*)          as golos
from todos
inner join public.competicoes c
  on c.nome = todos.competicao_nome
  and (c.categoria_id = todos.categoria_id or todos.categoria_id is null)
left join public.categorias cat on cat.id = c.categoria_id
where c.publicada = true and c.ativa = true
group by c.id, c.nome, c.slug, c.categoria_id, cat.slug, cat.nome, cat.emoji, todos.jogador
order by c.nome, golos desc, todos.jogador;

grant select on public.top_marcadores to anon, authenticated;

-- ============================================================
-- 7. SEED de exemplo
-- ============================================================
insert into public.competicoes (nome, slug, categoria_id, pontos_vitoria, pontos_empate, pontos_derrota)
values
  (
    'Liga Nacional - Jornada 27',
    'liga-nacional-jornada-27',
    (select id from public.categorias where slug = 'futebol'),
    3, 1, 0
  ),
  (
    'Campeonato Nacional 2025/26',
    'campeonato-nacional-2025-26',
    (select id from public.categorias where slug = 'basketball'),
    2, 1, 0
  )
on conflict (slug) do nothing;

-- ============================================================
-- VERIFICAÇÃO
-- ============================================================
-- Tabela classificativa
select
  competicao_nome,
  equipa,
  jogos as J,
  vitorias as V,
  empates as E,
  derrotas as D,
  gm as GM,
  gs as GS,
  diferenca_golos as DG,
  pontos as Pts
from public.classificacao_publica;

-- Top marcadores
select
  competicao_nome,
  jogador,
  equipa,
  golos
from public.top_marcadores
limit 10;
