-- ============================================================
-- PODIUM — MIGRATION 006: Equipas e Jogadores
-- ============================================================
-- Cria entidades reutilizáveis para equipas e jogadores.
-- Migra os dados existentes (texto livre → IDs) e actualiza
-- todas as views/tabelas dependentes.
--
-- COMO CORRER:
--   Supabase Dashboard → SQL Editor → New query → colar tudo → Run
--
-- IDEMPOTENTE (com cuidado): pode correr múltiplas vezes; a
-- migração de dados textuais é guardada por checks de existência.
--
-- Pré-requisitos: migrations 003, 004 e 005 já corridas.
-- ============================================================

-- ============================================================
-- 1. TABELA: equipas (globais — uma equipa pode jogar várias modalidades)
-- ============================================================
create table if not exists public.equipas (
  id              bigint generated by default as identity primary key,
  nome            text not null,
  slug            text unique not null,
  cidade          text,
  fundada_em      int,                                    -- ano de fundação
  cores           text,                                   -- ex: "azul-amarelo"
  emblema_url     text,                                   -- URL do logo no Storage
  observacoes     text,
  criada_em       timestamptz default now(),
  actualizada_em  timestamptz default now()
);

create index if not exists idx_equipas_nome on public.equipas (lower(nome));
create unique index if not exists uniq_equipas_nome_lower
  on public.equipas (lower(nome));

drop trigger if exists trg_equipas_updated on public.equipas;
create trigger trg_equipas_updated
  before update on public.equipas
  for each row execute function public.handle_updated_at();

-- ============================================================
-- 2. TABELA: jogadores
-- ============================================================
create table if not exists public.jogadores (
  id              bigint generated by default as identity primary key,
  nome            text not null,
  apelido         text,                                   -- nome de jogo (ex: "Geny")
  data_nascimento date,
  posicao         text,                                   -- ex: "Avançado", "Base", "Líbero"
  numero_camisola int,                                    -- nº actual (referência rápida)
  foto_url        text,
  observacoes     text,
  criada_em       timestamptz default now(),
  actualizada_em  timestamptz default now()
);

create index if not exists idx_jogadores_nome on public.jogadores (lower(nome));

drop trigger if exists trg_jogadores_updated on public.jogadores;
create trigger trg_jogadores_updated
  before update on public.jogadores
  for each row execute function public.handle_updated_at();

-- ============================================================
-- 3. TABELA: jogadores_equipas (relação N:N com histórico)
-- ============================================================
create table if not exists public.jogadores_equipas (
  id              bigint generated by default as identity primary key,
  jogador_id      bigint not null references public.jogadores(id) on delete cascade,
  equipa_id       bigint not null references public.equipas(id) on delete cascade,
  desde           date,                                   -- data início (opcional)
  ate             date,                                   -- data fim (null = actual)
  numero_camisola int,
  observacoes     text,
  criada_em       timestamptz default now()
);

create index if not exists idx_je_jogador on public.jogadores_equipas (jogador_id);
create index if not exists idx_je_equipa  on public.jogadores_equipas (equipa_id);
create index if not exists idx_je_actual  on public.jogadores_equipas (jogador_id) where ate is null;

-- ============================================================
-- 4. ROW LEVEL SECURITY
-- ============================================================
alter table public.equipas              enable row level security;
alter table public.jogadores            enable row level security;
alter table public.jogadores_equipas    enable row level security;

drop policy if exists "equipas_public_read"     on public.equipas;
drop policy if exists "equipas_admin_write"     on public.equipas;
create policy "equipas_public_read"  on public.equipas for select using (true);
create policy "equipas_admin_write"  on public.equipas for all
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "jogadores_public_read"     on public.jogadores;
drop policy if exists "jogadores_admin_write"     on public.jogadores;
create policy "jogadores_public_read"  on public.jogadores for select using (true);
create policy "jogadores_admin_write"  on public.jogadores for all
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "je_public_read"     on public.jogadores_equipas;
drop policy if exists "je_admin_write"     on public.jogadores_equipas;
create policy "je_public_read"  on public.jogadores_equipas for select using (true);
create policy "je_admin_write"  on public.jogadores_equipas for all
  using (public.is_admin()) with check (public.is_admin());

-- ============================================================
-- 5. ADICIONAR colunas FK às tabelas existentes
--    (mantemos as colunas de texto durante a migração; depois
--    estarão lá só por retro-compatibilidade mas o front-end
--    passa a usar os IDs)
-- ============================================================

-- 5a. agenda_eventos
do $$
begin
  if not exists (select 1 from information_schema.columns
    where table_name = 'agenda_eventos' and column_name = 'equipa_casa_id') then
    alter table public.agenda_eventos
      add column equipa_casa_id bigint references public.equipas(id) on delete set null;
  end if;
  if not exists (select 1 from information_schema.columns
    where table_name = 'agenda_eventos' and column_name = 'equipa_fora_id') then
    alter table public.agenda_eventos
      add column equipa_fora_id bigint references public.equipas(id) on delete set null;
  end if;
  if not exists (select 1 from information_schema.columns
    where table_name = 'agenda_eventos' and column_name = 'mvp_id') then
    alter table public.agenda_eventos
      add column mvp_id bigint references public.jogadores(id) on delete set null;
  end if;
end $$;

-- 5b. resultados
do $$
begin
  if not exists (select 1 from information_schema.columns
    where table_name = 'resultados' and column_name = 'equipa_casa_id') then
    alter table public.resultados
      add column equipa_casa_id bigint references public.equipas(id) on delete set null;
  end if;
  if not exists (select 1 from information_schema.columns
    where table_name = 'resultados' and column_name = 'equipa_fora_id') then
    alter table public.resultados
      add column equipa_fora_id bigint references public.equipas(id) on delete set null;
  end if;
  if not exists (select 1 from information_schema.columns
    where table_name = 'resultados' and column_name = 'mvp_id') then
    alter table public.resultados
      add column mvp_id bigint references public.jogadores(id) on delete set null;
  end if;
end $$;

-- 5c. classificacoes_ajustes
do $$
begin
  if not exists (select 1 from information_schema.columns
    where table_name = 'classificacoes_ajustes' and column_name = 'equipa_id') then
    alter table public.classificacoes_ajustes
      add column equipa_id bigint references public.equipas(id) on delete cascade;
  end if;
end $$;

-- ============================================================
-- 6. MIGRAÇÃO DE DADOS — extrair equipas únicas dos campos texto
-- ============================================================
-- 6a. Inserir equipas únicas dos resultados + agenda
insert into public.equipas (nome, slug)
select distinct
  trim(equipa) as nome,
  lower(regexp_replace(
    regexp_replace(
      translate(trim(equipa),
        'áàâãäåÁÀÂÃÄÅéèêëÉÈÊËíìîïÍÌÎÏóòôõöÓÒÔÕÖúùûüÚÙÛÜçÇñÑ',
        'aaaaaaAAAAAAeeeeEEEEiiiiIIIIoooooOOOOOuuuuUUUUcCnN'),
      '[^a-zA-Z0-9\s-]', '', 'g'),
    '\s+', '-', 'g'
  )) as slug
from (
  select equipa_casa as equipa from public.agenda_eventos where equipa_casa is not null
  union
  select equipa_fora from public.agenda_eventos where equipa_fora is not null
  union
  select equipa_casa from public.resultados where equipa_casa is not null
  union
  select equipa_fora from public.resultados where equipa_fora is not null
  union
  select equipa from public.classificacoes_ajustes where equipa is not null
) as fontes
where trim(equipa) <> ''
on conflict do nothing;

-- 6b. Ligar agenda_eventos aos novos IDs
update public.agenda_eventos e
set equipa_casa_id = eq.id
from public.equipas eq
where e.equipa_casa is not null
  and e.equipa_casa_id is null
  and lower(trim(e.equipa_casa)) = lower(eq.nome);

update public.agenda_eventos e
set equipa_fora_id = eq.id
from public.equipas eq
where e.equipa_fora is not null
  and e.equipa_fora_id is null
  and lower(trim(e.equipa_fora)) = lower(eq.nome);

-- 6c. Ligar resultados
update public.resultados r
set equipa_casa_id = eq.id
from public.equipas eq
where r.equipa_casa is not null
  and r.equipa_casa_id is null
  and lower(trim(r.equipa_casa)) = lower(eq.nome);

update public.resultados r
set equipa_fora_id = eq.id
from public.equipas eq
where r.equipa_fora is not null
  and r.equipa_fora_id is null
  and lower(trim(r.equipa_fora)) = lower(eq.nome);

-- 6d. Ligar ajustes
update public.classificacoes_ajustes a
set equipa_id = eq.id
from public.equipas eq
where a.equipa is not null
  and a.equipa_id is null
  and lower(trim(a.equipa)) = lower(eq.nome);

-- ============================================================
-- 6e. MIGRAR JOGADORES DE TEXTO PARA TABELA
-- ============================================================
-- Inserir jogadores únicos do MVP + estatísticas
do $$
declare
  e_record record;
  r_record record;
  stat jsonb;
  jogador_nome text;
  jogador_id_var bigint;
begin
  -- MVP da agenda
  for e_record in select id, mvp from public.agenda_eventos
    where mvp is not null and trim(mvp) <> '' and mvp_id is null
  loop
    insert into public.jogadores (nome) values (trim(e_record.mvp))
    on conflict do nothing;
    select id into jogador_id_var from public.jogadores
      where lower(nome) = lower(trim(e_record.mvp)) limit 1;
    update public.agenda_eventos set mvp_id = jogador_id_var where id = e_record.id;
  end loop;

  -- MVP dos resultados
  for r_record in select id, mvp from public.resultados
    where mvp is not null and trim(mvp) <> '' and mvp_id is null
  loop
    insert into public.jogadores (nome) values (trim(r_record.mvp))
    on conflict do nothing;
    select id into jogador_id_var from public.jogadores
      where lower(nome) = lower(trim(r_record.mvp)) limit 1;
    update public.resultados set mvp_id = jogador_id_var where id = r_record.id;
  end loop;

  -- Jogadores das estatísticas (golos)
  for r_record in select estatisticas from public.resultados where estatisticas is not null
  loop
    for stat in select jsonb_array_elements(r_record.estatisticas)
    loop
      jogador_nome := stat->>'jogador';
      if jogador_nome is not null and trim(jogador_nome) <> '' then
        insert into public.jogadores (nome) values (trim(jogador_nome))
        on conflict do nothing;
      end if;
    end loop;
  end loop;

  for e_record in select estatisticas from public.agenda_eventos where estatisticas is not null
  loop
    for stat in select jsonb_array_elements(e_record.estatisticas)
    loop
      jogador_nome := stat->>'jogador';
      if jogador_nome is not null and trim(jogador_nome) <> '' then
        insert into public.jogadores (nome) values (trim(jogador_nome))
        on conflict do nothing;
      end if;
    end loop;
  end loop;
end $$;

-- ============================================================
-- 6f. INFERIR jogadores_equipas a partir das estatísticas
--    (jogador X marcou pela equipa casa Y → vínculo X-Y)
-- ============================================================
with golos_extraidos as (
  select
    trim(stat->>'jogador') as jogador_nome,
    case stat->>'equipa'
      when 'casa' then r.equipa_casa_id
      when 'fora' then r.equipa_fora_id
    end as equipa_id
  from public.resultados r
  cross join lateral jsonb_array_elements(coalesce(r.estatisticas, '[]'::jsonb)) as stat
  where stat->>'tipo' = 'golo'
    and stat->>'jogador' is not null
    and trim(stat->>'jogador') <> ''
)
insert into public.jogadores_equipas (jogador_id, equipa_id)
select distinct j.id, ge.equipa_id
from golos_extraidos ge
join public.jogadores j on lower(j.nome) = lower(ge.jogador_nome)
where ge.equipa_id is not null
  and not exists (
    select 1 from public.jogadores_equipas je
    where je.jogador_id = j.id and je.equipa_id = ge.equipa_id
  );

-- ============================================================
-- 7. VIEWS — actualizar para usar IDs (com fallback ao texto)
-- ============================================================

-- 7a. resultados_publicos com IDs e nomes via JOIN
drop view if exists public.resultados_publicos cascade;

create view public.resultados_publicos as
select
  'agenda'::text   as origem,
  e.id             as id,
  e.titulo         as titulo,
  e.competicao     as competicao,
  e.data_evento    as data_evento,
  e.local          as local,
  e.cidade         as cidade,
  e.equipa_casa_id,
  e.equipa_fora_id,
  coalesce(eqc.nome, e.equipa_casa) as equipa_casa,
  coalesce(eqf.nome, e.equipa_fora) as equipa_fora,
  e.resultado_casa,
  e.resultado_fora,
  e.mvp_id,
  coalesce(jmvp.nome, e.mvp) as mvp,
  null::text       as observacoes,
  e.estatisticas,
  e.destaque,
  c.slug           as categoria_slug,
  c.nome           as categoria_nome,
  c.emoji          as categoria_emoji,
  c.cor            as categoria_cor
from public.agenda_eventos e
left join public.categorias c    on c.id   = e.categoria_id
left join public.equipas eqc     on eqc.id = e.equipa_casa_id
left join public.equipas eqf     on eqf.id = e.equipa_fora_id
left join public.jogadores jmvp  on jmvp.id = e.mvp_id
where e.publicado = true
  and e.status = 'terminado'
  and e.resultado_casa is not null
  and e.resultado_fora is not null

union all

select
  'manual'::text as origem,
  r.id, r.titulo, r.competicao, r.data_evento, r.local, r.cidade,
  r.equipa_casa_id,
  r.equipa_fora_id,
  coalesce(eqc.nome, r.equipa_casa) as equipa_casa,
  coalesce(eqf.nome, r.equipa_fora) as equipa_fora,
  r.resultado_casa, r.resultado_fora,
  r.mvp_id,
  coalesce(jmvp.nome, r.mvp) as mvp,
  r.observacoes, r.estatisticas, r.destaque,
  c.slug as categoria_slug, c.nome as categoria_nome,
  c.emoji as categoria_emoji, c.cor as categoria_cor
from public.resultados r
left join public.categorias c    on c.id   = r.categoria_id
left join public.equipas eqc     on eqc.id = r.equipa_casa_id
left join public.equipas eqf     on eqf.id = r.equipa_fora_id
left join public.jogadores jmvp  on jmvp.id = r.mvp_id
where r.publicado = true

order by data_evento desc;

grant select on public.resultados_publicos to anon, authenticated;

-- 7b. agenda_publica idem
drop view if exists public.agenda_publica cascade;

create view public.agenda_publica as
select
  e.id, e.titulo, e.descricao, e.data_evento, e.duracao_min,
  e.local, e.cidade,
  e.equipa_casa_id, e.equipa_fora_id,
  coalesce(eqc.nome, e.equipa_casa) as equipa_casa,
  coalesce(eqf.nome, e.equipa_fora) as equipa_fora,
  e.competicao, e.status,
  e.resultado_casa, e.resultado_fora,
  e.destaque,
  c.slug as categoria_slug, c.nome as categoria_nome,
  c.emoji as categoria_emoji, c.cor as categoria_cor
from public.agenda_eventos e
left join public.categorias c on c.id = e.categoria_id
left join public.equipas eqc  on eqc.id = e.equipa_casa_id
left join public.equipas eqf  on eqf.id = e.equipa_fora_id
where e.publicado = true
order by e.data_evento asc;

grant select on public.agenda_publica to anon, authenticated;

-- 7c. jogos_classificacao usa IDs agora
drop view if exists public.jogos_classificacao cascade;

create view public.jogos_classificacao as
select
  e.competicao         as competicao_nome,
  coalesce(eqc.nome, e.equipa_casa) as equipa_casa,
  coalesce(eqf.nome, e.equipa_fora) as equipa_fora,
  e.equipa_casa_id,
  e.equipa_fora_id,
  e.resultado_casa,
  e.resultado_fora,
  e.categoria_id,
  e.data_evento
from public.agenda_eventos e
left join public.equipas eqc on eqc.id = e.equipa_casa_id
left join public.equipas eqf on eqf.id = e.equipa_fora_id
where e.publicado = true
  and e.status = 'terminado'
  and e.resultado_casa is not null
  and e.resultado_fora is not null
  and e.competicao is not null
  and (e.equipa_casa_id is not null or e.equipa_casa is not null)
  and (e.equipa_fora_id is not null or e.equipa_fora is not null)

union all

select
  r.competicao         as competicao_nome,
  coalesce(eqc.nome, r.equipa_casa) as equipa_casa,
  coalesce(eqf.nome, r.equipa_fora) as equipa_fora,
  r.equipa_casa_id,
  r.equipa_fora_id,
  r.resultado_casa,
  r.resultado_fora,
  r.categoria_id,
  r.data_evento
from public.resultados r
left join public.equipas eqc on eqc.id = r.equipa_casa_id
left join public.equipas eqf on eqf.id = r.equipa_fora_id
where r.publicado = true and r.competicao is not null;

grant select on public.jogos_classificacao to anon, authenticated;

-- 7d. classificacao_publica re-criar (depende de jogos_classificacao)
drop view if exists public.classificacao_publica cascade;

create view public.classificacao_publica as
with
  jogos_expandidos as (
    select
      j.competicao_nome, j.categoria_id,
      j.equipa_casa as equipa, j.resultado_casa as gm, j.resultado_fora as gs,
      case when j.resultado_casa > j.resultado_fora then 'V'
           when j.resultado_casa < j.resultado_fora then 'D'
           else 'E' end as resultado
    from public.jogos_classificacao j
    union all
    select
      j.competicao_nome, j.categoria_id,
      j.equipa_fora as equipa, j.resultado_fora as gm, j.resultado_casa as gs,
      case when j.resultado_fora > j.resultado_casa then 'V'
           when j.resultado_fora < j.resultado_casa then 'D'
           else 'E' end as resultado
    from public.jogos_classificacao j
  ),
  agregado as (
    select
      je.competicao_nome, je.categoria_id, je.equipa,
      count(*) as jogos,
      count(*) filter (where je.resultado = 'V') as vitorias,
      count(*) filter (where je.resultado = 'E') as empates,
      count(*) filter (where je.resultado = 'D') as derrotas,
      coalesce(sum(je.gm), 0) as gm,
      coalesce(sum(je.gs), 0) as gs
    from jogos_expandidos je
    group by je.competicao_nome, je.categoria_id, je.equipa
  )
select
  c.id            as competicao_id,
  c.nome          as competicao_nome,
  c.slug          as competicao_slug,
  c.categoria_id,
  cat.slug        as categoria_slug,
  cat.nome        as categoria_nome,
  cat.emoji       as categoria_emoji,
  cat.cor         as categoria_cor,
  ag.equipa,
  ag.jogos, ag.vitorias, ag.empates, ag.derrotas,
  ag.gm, ag.gs,
  (ag.gm - ag.gs) as diferenca_golos,
  (ag.vitorias * c.pontos_vitoria
   + ag.empates  * c.pontos_empate
   + ag.derrotas * c.pontos_derrota
   + coalesce(aj.ajuste_total, 0)) as pontos,
  coalesce(aj.ajuste_total, 0) as ajuste_pontos
from public.competicoes c
left join public.categorias cat on cat.id = c.categoria_id
inner join agregado ag
  on ag.competicao_nome = c.nome
  and (ag.categoria_id = c.categoria_id or ag.categoria_id is null)
left join (
  select
    a.competicao_id,
    coalesce(eq.nome, a.equipa) as equipa_nome,
    sum(a.pontos) as ajuste_total
  from public.classificacoes_ajustes a
  left join public.equipas eq on eq.id = a.equipa_id
  group by a.competicao_id, coalesce(eq.nome, a.equipa)
) aj on aj.competicao_id = c.id and aj.equipa_nome = ag.equipa
where c.publicada = true and c.ativa = true
order by c.nome, pontos desc, diferenca_golos desc, gm desc, ag.equipa;

grant select on public.classificacao_publica to anon, authenticated;

-- 7e. top_marcadores: extrair de estatísticas usando jogador (texto OU id)
drop view if exists public.top_marcadores cascade;

create view public.top_marcadores as
with
  golos_agenda as (
    select
      e.competicao              as competicao_nome,
      e.categoria_id,
      coalesce(stat->>'jogador_nome', stat->>'jogador') as jogador_nome,
      nullif(stat->>'jogador_id', '')::bigint as jogador_id,
      stat->>'equipa'           as equipa_lado,
      case stat->>'equipa'
        when 'casa' then coalesce(eqc.nome, e.equipa_casa)
        when 'fora' then coalesce(eqf.nome, e.equipa_fora)
      end as equipa
    from public.agenda_eventos e
    left join public.equipas eqc on eqc.id = e.equipa_casa_id
    left join public.equipas eqf on eqf.id = e.equipa_fora_id
    cross join lateral jsonb_array_elements(coalesce(e.estatisticas, '[]'::jsonb)) as stat
    where e.publicado = true and e.status = 'terminado'
      and stat->>'tipo' = 'golo'
      and (stat->>'jogador' is not null or stat->>'jogador_id' is not null)
  ),
  golos_manuais as (
    select
      r.competicao              as competicao_nome,
      r.categoria_id,
      coalesce(stat->>'jogador_nome', stat->>'jogador') as jogador_nome,
      nullif(stat->>'jogador_id', '')::bigint as jogador_id,
      stat->>'equipa'           as equipa_lado,
      case stat->>'equipa'
        when 'casa' then coalesce(eqc.nome, r.equipa_casa)
        when 'fora' then coalesce(eqf.nome, r.equipa_fora)
      end as equipa
    from public.resultados r
    left join public.equipas eqc on eqc.id = r.equipa_casa_id
    left join public.equipas eqf on eqf.id = r.equipa_fora_id
    cross join lateral jsonb_array_elements(coalesce(r.estatisticas, '[]'::jsonb)) as stat
    where r.publicado = true
      and stat->>'tipo' = 'golo'
      and (stat->>'jogador' is not null or stat->>'jogador_id' is not null)
  ),
  todos as (
    select * from golos_agenda
    union all
    select * from golos_manuais
  ),
  todos_resolvidos as (
    select
      t.competicao_nome,
      t.categoria_id,
      t.jogador_id,
      coalesce(j.nome, t.jogador_nome) as jogador,
      t.equipa
    from todos t
    left join public.jogadores j on j.id = t.jogador_id
  )
select
  c.id              as competicao_id,
  c.nome            as competicao_nome,
  c.slug            as competicao_slug,
  c.categoria_id,
  cat.slug          as categoria_slug,
  cat.nome          as categoria_nome,
  cat.emoji         as categoria_emoji,
  tr.jogador,
  tr.jogador_id,
  max(tr.equipa)    as equipa,
  count(*)          as golos
from todos_resolvidos tr
inner join public.competicoes c
  on c.nome = tr.competicao_nome
  and (c.categoria_id = tr.categoria_id or tr.categoria_id is null)
left join public.categorias cat on cat.id = c.categoria_id
where c.publicada = true and c.ativa = true
  and tr.jogador is not null
group by c.id, c.nome, c.slug, c.categoria_id,
         cat.slug, cat.nome, cat.emoji,
         tr.jogador, tr.jogador_id
order by c.nome, golos desc, tr.jogador;

grant select on public.top_marcadores to anon, authenticated;

-- ============================================================
-- 8. VIEW: jogadores_actuais — jogador + equipa actual + categoria
-- ============================================================
drop view if exists public.jogadores_actuais cascade;

create view public.jogadores_actuais as
select
  j.id,
  j.nome,
  j.apelido,
  j.posicao,
  j.numero_camisola,
  j.foto_url,
  je.equipa_id,
  e.nome as equipa_nome,
  je.numero_camisola as numero_actual
from public.jogadores j
left join lateral (
  select * from public.jogadores_equipas je
  where je.jogador_id = j.id
    and (je.ate is null or je.ate >= current_date)
  order by je.desde desc nulls last
  limit 1
) je on true
left join public.equipas e on e.id = je.equipa_id;

grant select on public.jogadores_actuais to anon, authenticated;

-- ============================================================
-- VERIFICAÇÃO
-- ============================================================
select
  (select count(*) from public.equipas)            as total_equipas,
  (select count(*) from public.jogadores)          as total_jogadores,
  (select count(*) from public.jogadores_equipas)  as total_vinculos,
  (select count(*) from public.agenda_eventos where equipa_casa_id is not null) as eventos_migrados,
  (select count(*) from public.resultados where equipa_casa_id is not null)     as resultados_migrados;
