-- ============================================================
-- PODIUM — MIGRATION 003: Agenda desportiva
-- ============================================================
-- Cria tabela `agenda_eventos` para gerir eventos desportivos
-- (jogos, torneios, finais, etc.) com data, hora, local e equipas.
--
-- COMO CORRER:
--   Supabase Dashboard → SQL Editor → New query → colar tudo → Run
--
-- IDEMPOTENTE: pode correr múltiplas vezes sem problemas.
-- ============================================================

-- ============================================================
-- 1. TABELA: agenda_eventos
-- ============================================================
create table if not exists public.agenda_eventos (
  id              bigint generated by default as identity primary key,
  titulo          text not null,
  descricao       text,
  categoria_id    bigint references public.categorias(id) on delete set null,
  data_evento     timestamptz not null,                   -- data + hora do evento
  duracao_min     int default 90,                         -- duração estimada em minutos
  local           text,                                   -- ex: "Estádio da Machava"
  cidade          text,                                   -- ex: "Maputo"
  equipa_casa     text,                                   -- ex: "Costa do Sol" (opcional)
  equipa_fora     text,                                   -- ex: "Liga Muçulmana" (opcional)
  competicao      text,                                   -- ex: "Liga Nacional - Jornada 28"
  status          text check (status in ('agendado', 'em_curso', 'terminado', 'cancelado', 'adiado'))
                  default 'agendado',
  resultado_casa  int,                                    -- resultado equipa casa (após jogo)
  resultado_fora  int,                                    -- resultado equipa fora (após jogo)
  destaque        boolean default false,                  -- evento em destaque
  publicado       boolean default true,                   -- visível no site público
  criada_em       timestamptz default now(),
  actualizada_em  timestamptz default now(),
  criada_por      uuid references auth.users(id) on delete set null
);

create index if not exists idx_agenda_data       on public.agenda_eventos (data_evento);
create index if not exists idx_agenda_categoria  on public.agenda_eventos (categoria_id);
create index if not exists idx_agenda_status     on public.agenda_eventos (status);
create index if not exists idx_agenda_publicado  on public.agenda_eventos (publicado);

-- ============================================================
-- 2. TRIGGER: actualizar `actualizada_em` automaticamente
-- ============================================================
drop trigger if exists trg_agenda_updated on public.agenda_eventos;
create trigger trg_agenda_updated
  before update on public.agenda_eventos
  for each row execute function public.handle_updated_at();

-- ============================================================
-- 3. ROW LEVEL SECURITY
-- ============================================================
alter table public.agenda_eventos enable row level security;

drop policy if exists "agenda_public_read"     on public.agenda_eventos;
drop policy if exists "agenda_admin_read_all"  on public.agenda_eventos;
drop policy if exists "agenda_admin_write"     on public.agenda_eventos;

-- Leitura pública só dos eventos publicados
create policy "agenda_public_read"
  on public.agenda_eventos for select
  using (publicado = true);

-- Admins veem tudo
create policy "agenda_admin_read_all"
  on public.agenda_eventos for select
  using (public.is_admin());

-- Admins podem criar/editar/eliminar
create policy "agenda_admin_write"
  on public.agenda_eventos for all
  using (public.is_admin())
  with check (public.is_admin());

-- ============================================================
-- 4. VIEW: agenda pública com info da categoria embutida
-- ============================================================
drop view if exists public.agenda_publica;

create view public.agenda_publica as
select
  e.id,
  e.titulo,
  e.descricao,
  e.data_evento,
  e.duracao_min,
  e.local,
  e.cidade,
  e.equipa_casa,
  e.equipa_fora,
  e.competicao,
  e.status,
  e.resultado_casa,
  e.resultado_fora,
  e.destaque,
  c.slug  as categoria_slug,
  c.nome  as categoria_nome,
  c.emoji as categoria_emoji,
  c.cor   as categoria_cor
from public.agenda_eventos e
left join public.categorias c on c.id = e.categoria_id
where e.publicado = true
order by e.data_evento asc;

grant select on public.agenda_publica to anon, authenticated;

-- ============================================================
-- 5. SEED DE EXEMPLO (opcional — remover se não precisar)
-- ============================================================
insert into public.agenda_eventos
  (titulo, categoria_id, data_evento, local, cidade, competicao, destaque)
values
  (
    'Campeonato Nacional — Fase Final',
    (select id from public.categorias where slug = 'basketball'),
    now() + interval '15 days',
    'Pavilhão de Maxaquene',
    'Maputo',
    'Campeonato Nacional 2026',
    true
  ),
  (
    'Liga Nacional — Jornada 28',
    (select id from public.categorias where slug = 'futebol'),
    now() + interval '22 days',
    'Estádio da Machava',
    'Maputo',
    'Liga Nacional 2025/26',
    false
  ),
  (
    'Open de Moçambique',
    (select id from public.categorias where slug = 'tennis'),
    now() + interval '35 days',
    'Clube de Ténis',
    'Maputo',
    'Open de Moçambique 2026',
    true
  ),
  (
    'Final da Taça de Moçambique',
    (select id from public.categorias where slug = 'futebol'),
    now() + interval '48 days',
    'Estádio Nacional do Zimpeto',
    'Maputo',
    'Taça de Moçambique 2026',
    true
  )
on conflict do nothing;

-- ============================================================
-- VERIFICAÇÃO
-- ============================================================
-- Esperado: ver os 4 eventos do seed (ou os seus próprios)
select
  id,
  titulo,
  to_char(data_evento, 'DD/MM/YYYY HH24:MI') as data,
  cidade,
  status
from public.agenda_eventos
order by data_evento;
