-- ============================================================
-- PODIUM — SCHEMA SUPABASE
-- Executar este ficheiro no SQL Editor do Supabase:
--   Dashboard Supabase → SQL Editor → New query → colar tudo → Run
-- ============================================================

-- ---------- EXTENSIONS ----------
create extension if not exists "uuid-ossp";
create extension if not exists "unaccent";         -- para pesquisa sem acentos
create extension if not exists "pg_trgm";          -- para pesquisa fuzzy

-- ============================================================
-- 1. TABELA: categorias
-- ============================================================
create table if not exists public.categorias (
  id         bigint generated by default as identity primary key,
  slug       text unique not null,           -- 'futebol', 'basketball', etc
  nome       text not null,
  emoji      text default '📰',
  cor        text default '#e63329',         -- cor hex associada
  ordem      int default 0,
  criada_em  timestamptz default now()
);

-- Seed inicial de categorias
insert into public.categorias (slug, nome, emoji, cor, ordem) values
  ('futebol',    'Futebol',    '⚽', '#1a9e4d', 1),
  ('basketball', 'Basketball', '🏀', '#ea580c', 2),
  ('tennis',     'Ténis',      '🎾', '#22c55e', 3),
  ('atletismo',  'Atletismo',  '🏃', '#3b82f6', 4),
  ('motorsport', 'Motorsport', '🏎️', '#dc2626', 5),
  ('volei',      'Voleibol',   '🏐', '#a855f7', 6)
on conflict (slug) do nothing;

-- ============================================================
-- 2. TABELA: noticias
-- ============================================================
create table if not exists public.noticias (
  id                bigint generated by default as identity primary key,
  titulo            text not null,
  slug              text unique,                             -- gerado automaticamente
  resumo            text not null,
  conteudo          text[] not null default array[]::text[],  -- array de parágrafos
  imagem_url        text,                                     -- URL da imagem no Storage
  categoria_id      bigint references public.categorias(id) on delete set null,
  autor             text not null default 'Equipa Podium',
  destaque          boolean default false,                    -- aparece no hero slider
  publicada         boolean default true,                     -- publicada vs rascunho
  data_publicacao   timestamptz default now(),
  criada_em         timestamptz default now(),
  actualizada_em    timestamptz default now(),
  criada_por        uuid references auth.users(id) on delete set null,
  views             int default 0
);

create index if not exists idx_noticias_data        on public.noticias (data_publicacao desc);
create index if not exists idx_noticias_categoria   on public.noticias (categoria_id);
create index if not exists idx_noticias_destaque    on public.noticias (destaque) where destaque = true;
create index if not exists idx_noticias_publicada   on public.noticias (publicada);
create index if not exists idx_noticias_titulo_trgm on public.noticias using gin (titulo gin_trgm_ops);
create index if not exists idx_noticias_com_imagem  on public.noticias (data_publicacao desc) where imagem_url is not null;

-- ============================================================
-- 3. TRIGGER: actualizar `actualizada_em` automaticamente
-- ============================================================
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.actualizada_em = now();
  return new;
end;
$$;

drop trigger if exists trg_noticias_updated on public.noticias;
create trigger trg_noticias_updated
  before update on public.noticias
  for each row execute function public.handle_updated_at();

-- ============================================================
-- 4. TRIGGER: gerar slug automaticamente a partir do título
-- ============================================================
create or replace function public.generate_slug(input_text text)
returns text
language plpgsql
immutable
as $$
begin
  return lower(
    regexp_replace(
      regexp_replace(
        unaccent(input_text),
        '[^a-zA-Z0-9\s-]', '', 'g'
      ),
      '\s+', '-', 'g'
    )
  );
end;
$$;

create or replace function public.noticia_set_slug()
returns trigger
language plpgsql
as $$
declare
  base_slug text;
  final_slug text;
  counter int := 0;
begin
  if new.slug is null or new.slug = '' then
    base_slug := public.generate_slug(new.titulo);
    final_slug := base_slug;
    -- garantir unicidade
    while exists (select 1 from public.noticias where slug = final_slug and id != coalesce(new.id, -1)) loop
      counter := counter + 1;
      final_slug := base_slug || '-' || counter;
    end loop;
    new.slug := final_slug;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_noticias_slug on public.noticias;
create trigger trg_noticias_slug
  before insert or update of titulo on public.noticias
  for each row execute function public.noticia_set_slug();

-- ============================================================
-- 5. TABELA: admin_users  (quem pode aceder ao dashboard)
-- ============================================================
create table if not exists public.admin_users (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  role       text check (role in ('admin', 'editor')) default 'editor',
  criado_em  timestamptz default now()
);

-- ============================================================
-- 6. FUNÇÃO: verificar se utilizador é admin
-- ============================================================
create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users where user_id = uid);
$$;

-- ============================================================
-- 7. ROW LEVEL SECURITY
-- ============================================================
alter table public.categorias   enable row level security;
alter table public.noticias     enable row level security;
alter table public.admin_users  enable row level security;

-- ----- CATEGORIAS: leitura pública; escrita só admins -----
drop policy if exists "categorias_public_read"  on public.categorias;
drop policy if exists "categorias_admin_write"  on public.categorias;

create policy "categorias_public_read"
  on public.categorias for select
  using (true);

create policy "categorias_admin_write"
  on public.categorias for all
  using (public.is_admin())
  with check (public.is_admin());

-- ----- NOTÍCIAS: leitura pública só das publicadas; admins vêem tudo -----
drop policy if exists "noticias_public_read"       on public.noticias;
drop policy if exists "noticias_admin_read_all"    on public.noticias;
drop policy if exists "noticias_admin_write"       on public.noticias;

create policy "noticias_public_read"
  on public.noticias for select
  using (publicada = true);

create policy "noticias_admin_read_all"
  on public.noticias for select
  using (public.is_admin());

create policy "noticias_admin_write"
  on public.noticias for all
  using (public.is_admin())
  with check (public.is_admin());

-- ----- ADMIN_USERS: cada admin vê-se a si; só admins podem adicionar outros -----
drop policy if exists "admin_users_self_read" on public.admin_users;
drop policy if exists "admin_users_manage"    on public.admin_users;

create policy "admin_users_self_read"
  on public.admin_users for select
  using (user_id = auth.uid() or public.is_admin());

create policy "admin_users_manage"
  on public.admin_users for all
  using (public.is_admin())
  with check (public.is_admin());

-- ============================================================
-- 8. STORAGE BUCKET para imagens das notícias
-- ============================================================
-- Criar bucket (executar via UI também é possível:
--   Storage → Create bucket → name: 'noticias-imagens' → public)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'noticias-imagens',
  'noticias-imagens',
  true,
  5242880,                                                                       -- 5 MB
  array['image/jpeg','image/png','image/webp','image/gif','image/svg+xml']
)
on conflict (id) do update set
  file_size_limit       = excluded.file_size_limit,
  allowed_mime_types    = excluded.allowed_mime_types;

-- Policies do bucket
drop policy if exists "storage_noticias_public_read" on storage.objects;
drop policy if exists "storage_noticias_admin_write" on storage.objects;
drop policy if exists "storage_noticias_admin_update" on storage.objects;
drop policy if exists "storage_noticias_admin_delete" on storage.objects;

create policy "storage_noticias_public_read"
  on storage.objects for select
  using (bucket_id = 'noticias-imagens');

create policy "storage_noticias_admin_write"
  on storage.objects for insert
  with check (bucket_id = 'noticias-imagens' and public.is_admin());

create policy "storage_noticias_admin_update"
  on storage.objects for update
  using (bucket_id = 'noticias-imagens' and public.is_admin());

create policy "storage_noticias_admin_delete"
  on storage.objects for delete
  using (bucket_id = 'noticias-imagens' and public.is_admin());

-- ============================================================
-- 9. VIEW: notícias com info da categoria embutida (conveniência)
-- ============================================================
create or replace view public.noticias_publicas as
select
  n.id,
  n.titulo,
  n.slug,
  n.resumo,
  n.conteudo,
  n.imagem_url,
  n.autor,
  n.destaque,
  n.data_publicacao,
  n.views,
  c.slug  as categoria_slug,
  c.nome  as categoria_nome,
  c.emoji as categoria_emoji,
  c.cor   as categoria_cor
from public.noticias n
left join public.categorias c on c.id = n.categoria_id
where n.publicada = true
order by n.data_publicacao desc;

grant select on public.noticias_publicas to anon, authenticated;

-- ============================================================
-- 10. FUNÇÃO RPC: incrementar views
-- ============================================================
create or replace function public.incrementar_views(noticia_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.noticias set views = views + 1 where id = noticia_id;
$$;

grant execute on function public.incrementar_views to anon, authenticated;

-- ============================================================
-- 11. FUNÇÃO: limpar imagens órfãs do Storage
-- ============================================================
-- Útil para manutenção: remove ficheiros do Storage que já não
-- pertencem a nenhuma notícia (após edições ou eliminações).
-- Só admins podem executar.
--
-- USO: select * from public.limpar_imagens_orfas();
create or replace function public.limpar_imagens_orfas()
returns table (filename text, deleted boolean)
language plpgsql
security definer
set search_path = public, storage
as $$
declare
  obj record;
  is_used boolean;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem limpar imagens órfãs';
  end if;

  for obj in
    select name from storage.objects where bucket_id = 'noticias-imagens'
  loop
    select exists (
      select 1 from public.noticias
      where imagem_url like '%/' || obj.name
    ) into is_used;

    if not is_used then
      delete from storage.objects
      where bucket_id = 'noticias-imagens' and name = obj.name;

      filename := obj.name;
      deleted := true;
      return next;
    end if;
  end loop;
  return;
end;
$$;

revoke all on function public.limpar_imagens_orfas() from public;
grant execute on function public.limpar_imagens_orfas() to authenticated;

-- ============================================================
-- SEED DE EXEMPLO (opcional — remover se não precisar)
-- ============================================================
insert into public.noticias (titulo, resumo, conteudo, categoria_id, autor, destaque, data_publicacao) values
  (
    'Clássico decisivo termina em vitória emocionante',
    'O confronto entre rivais foi marcado por grande intensidade do início ao fim, com uma das equipas a destacar-se e garantir uma vitória merecida.',
    array[
      'O pavilhão de Maxaquene recebeu na noite de ontem um dos clássicos mais aguardados da temporada.',
      'A primeira parte terminou com uma diferença mínima no marcador, sinal do equilíbrio que se verificou em campo.',
      'Com esta vitória, a equipa consolida a liderança do campeonato.'
    ],
    (select id from public.categorias where slug = 'basketball'),
    'Ana Cossa',
    true,
    now() - interval '1 day'
  ),
  (
    'Jovem talentosa destaca-se na liga nacional',
    'Um novo nome começa a ganhar destaque após uma atuação impressionante.',
    array[
      'Aos apenas 19 anos, a jogadora tem impressionado críticos e adeptos.',
      'Na última jornada, foi decisiva ao assistir para dois golos e marcar o terceiro.'
    ],
    (select id from public.categorias where slug = 'futebol'),
    'Pedro Antunes',
    true,
    now() - interval '2 days'
  ),
  (
    'Preparação intensa para o próximo torneio internacional',
    'As equipas já estão focadas nos treinos e estratégias para representar o país.',
    array[
      'O Open de Moçambique aproxima-se e os nossos representantes intensificam a preparação.',
      'A comissão técnica mostra-se confiante nas escolhas feitas.'
    ],
    (select id from public.categorias where slug = 'tennis'),
    'Xavier Macuacua',
    true,
    now() - interval '5 days'
  )
on conflict do nothing;

-- ============================================================
-- FIM — para tornar um utilizador administrador:
--   1. Criar utilizador em Authentication → Users → Invite user
--   2. Copiar o user UUID
--   3. Correr:
--        insert into public.admin_users (user_id, role) values ('<UUID>', 'admin');
-- ============================================================
