-- ============================================================
-- PODIUM — MIGRATION 004: Resultados desportivos
-- ============================================================
-- Cria tabela `resultados` para resultados que podem não vir de
-- eventos pré-agendados (jogos amigáveis, resultados históricos, etc.)
-- e adiciona campos de estatística aos eventos da agenda.
--
-- Cria também uma VIEW unificada `resultados_publicos` que junta:
--   - Eventos da agenda com status='terminado' que tenham resultado
--   - Entradas da nova tabela `resultados`
-- Essa view é o ponto único de leitura no site público.
--
-- COMO CORRER:
--   Supabase Dashboard → SQL Editor → New query → colar tudo → Run
--
-- IDEMPOTENTE: pode correr múltiplas vezes sem problemas.
-- Pré-requisito: migration_003_agenda.sql já corrida.
-- ============================================================

-- ============================================================
-- 1. Adicionar campos de estatística à `agenda_eventos`
--    (mvp + observações). Já existe resultado_casa/resultado_fora.
-- ============================================================
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'agenda_eventos' and column_name = 'mvp'
  ) then
    alter table public.agenda_eventos add column mvp text;
    raise notice 'Coluna mvp adicionada a agenda_eventos';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'agenda_eventos' and column_name = 'estatisticas'
  ) then
    alter table public.agenda_eventos add column estatisticas jsonb default '[]'::jsonb;
    raise notice 'Coluna estatisticas adicionada a agenda_eventos';
  end if;
end $$;

-- ============================================================
-- 2. TABELA: resultados (independentes da agenda)
-- ============================================================
create table if not exists public.resultados (
  id              bigint generated by default as identity primary key,
  titulo          text not null,                          -- ex: "Costa do Sol vs Liga Muçulmana"
  categoria_id    bigint references public.categorias(id) on delete set null,
  data_evento     timestamptz not null,
  competicao      text,                                   -- ex: "Liga Nacional - Jornada 28"
  local           text,
  cidade          text,

  equipa_casa     text not null,
  equipa_fora     text not null,
  resultado_casa  int not null,
  resultado_fora  int not null,

  mvp             text,                                   -- jogador destaque
  observacoes     text,                                   -- breve resumo

  -- Estatísticas detalhadas em formato JSON
  -- Exemplo: [{"minuto": 23, "tipo": "golo", "equipa": "casa", "jogador": "João"}, ...]
  estatisticas    jsonb default '[]'::jsonb,

  publicado       boolean default true,
  destaque        boolean default false,
  criada_em       timestamptz default now(),
  actualizada_em  timestamptz default now(),
  criada_por      uuid references auth.users(id) on delete set null
);

create index if not exists idx_resultados_data       on public.resultados (data_evento desc);
create index if not exists idx_resultados_categoria  on public.resultados (categoria_id);
create index if not exists idx_resultados_publicado  on public.resultados (publicado);

-- ============================================================
-- 3. TRIGGER: actualizada_em
-- ============================================================
drop trigger if exists trg_resultados_updated on public.resultados;
create trigger trg_resultados_updated
  before update on public.resultados
  for each row execute function public.handle_updated_at();

-- ============================================================
-- 4. ROW LEVEL SECURITY
-- ============================================================
alter table public.resultados enable row level security;

drop policy if exists "resultados_public_read"     on public.resultados;
drop policy if exists "resultados_admin_read_all"  on public.resultados;
drop policy if exists "resultados_admin_write"     on public.resultados;

create policy "resultados_public_read"
  on public.resultados for select
  using (publicado = true);

create policy "resultados_admin_read_all"
  on public.resultados for select
  using (public.is_admin());

create policy "resultados_admin_write"
  on public.resultados for all
  using (public.is_admin())
  with check (public.is_admin());

-- ============================================================
-- 5. VIEW UNIFICADA: resultados_publicos
--    Junta:
--      • Eventos da agenda com status='terminado' que tenham marcador
--      • Resultados manuais publicados
--    Cada linha tem `origem` para saber a fonte ('agenda' | 'manual')
-- ============================================================
drop view if exists public.resultados_publicos;

create view public.resultados_publicos as
-- Fonte 1: eventos da agenda terminados COM resultado
select
  'agenda'::text   as origem,
  e.id             as id,
  e.titulo         as titulo,
  e.competicao     as competicao,
  e.data_evento    as data_evento,
  e.local          as local,
  e.cidade         as cidade,
  e.equipa_casa    as equipa_casa,
  e.equipa_fora    as equipa_fora,
  e.resultado_casa as resultado_casa,
  e.resultado_fora as resultado_fora,
  e.mvp            as mvp,
  null::text       as observacoes,
  e.estatisticas   as estatisticas,
  e.destaque       as destaque,
  c.slug           as categoria_slug,
  c.nome           as categoria_nome,
  c.emoji          as categoria_emoji,
  c.cor            as categoria_cor
from public.agenda_eventos e
left join public.categorias c on c.id = e.categoria_id
where e.publicado = true
  and e.status = 'terminado'
  and e.resultado_casa is not null
  and e.resultado_fora is not null

union all

-- Fonte 2: resultados manuais
select
  'manual'::text   as origem,
  r.id             as id,
  r.titulo         as titulo,
  r.competicao     as competicao,
  r.data_evento    as data_evento,
  r.local          as local,
  r.cidade         as cidade,
  r.equipa_casa    as equipa_casa,
  r.equipa_fora    as equipa_fora,
  r.resultado_casa as resultado_casa,
  r.resultado_fora as resultado_fora,
  r.mvp            as mvp,
  r.observacoes    as observacoes,
  r.estatisticas   as estatisticas,
  r.destaque       as destaque,
  c.slug           as categoria_slug,
  c.nome           as categoria_nome,
  c.emoji          as categoria_emoji,
  c.cor            as categoria_cor
from public.resultados r
left join public.categorias c on c.id = r.categoria_id
where r.publicado = true

order by data_evento desc;

grant select on public.resultados_publicos to anon, authenticated;

-- ============================================================
-- 6. SEED de exemplo (opcional)
-- ============================================================
insert into public.resultados (
  titulo, categoria_id, data_evento, competicao,
  local, cidade,
  equipa_casa, equipa_fora,
  resultado_casa, resultado_fora,
  mvp, observacoes, estatisticas, destaque
) values
  (
    'Costa do Sol vs Liga Muçulmana',
    (select id from public.categorias where slug = 'futebol'),
    now() - interval '5 days',
    'Liga Nacional - Jornada 27',
    'Estádio do Costa do Sol',
    'Maputo',
    'Costa do Sol', 'Liga Muçulmana',
    2, 1,
    'Geny Catamo',
    'Vitória sofrida do Costa do Sol num jogo equilibrado.',
    jsonb_build_array(
      jsonb_build_object('minuto', 23, 'tipo', 'golo', 'equipa', 'casa',  'jogador', 'Geny Catamo'),
      jsonb_build_object('minuto', 56, 'tipo', 'golo', 'equipa', 'fora',  'jogador', 'Telinho'),
      jsonb_build_object('minuto', 78, 'tipo', 'golo', 'equipa', 'casa',  'jogador', 'Reginaldo')
    ),
    true
  ),
  (
    'Maxaquene vs Ferroviário',
    (select id from public.categorias where slug = 'basketball'),
    now() - interval '12 days',
    'Campeonato Nacional 2025/26',
    'Pavilhão de Maxaquene',
    'Maputo',
    'Maxaquene', 'Ferroviário',
    78, 72,
    'Custódio Muchate',
    'Triplos decisivos no último período garantiram a vitória ao Maxaquene.',
    jsonb_build_array(
      jsonb_build_object('minuto', 10, 'tipo', 'periodo', 'casa', 18, 'fora', 22),
      jsonb_build_object('minuto', 20, 'tipo', 'periodo', 'casa', 35, 'fora', 38),
      jsonb_build_object('minuto', 30, 'tipo', 'periodo', 'casa', 56, 'fora', 55),
      jsonb_build_object('minuto', 40, 'tipo', 'periodo', 'casa', 78, 'fora', 72)
    ),
    false
  )
on conflict do nothing;

-- ============================================================
-- VERIFICAÇÃO
-- ============================================================
select
  origem,
  titulo,
  to_char(data_evento, 'DD/MM/YYYY') as data,
  equipa_casa || ' ' || resultado_casa || '-' || resultado_fora || ' ' || equipa_fora as marcador,
  categoria_slug
from public.resultados_publicos
order by data_evento desc
limit 10;
